





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using CodeTest.Foundation.ORM.Models;




namespace CodeTest.Feature.GenericCallout.Models.GlassModels
{


	/// <summary>
	/// I_Alternate_Callout_Parameter Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Alternate Callout/Rendering parameters/_alternate callout parameter</para>	
	/// <para>ID: 0876cc35-a32e-4baa-88d6-644ed9eebfd4</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Alternate_Callout_ParameterConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Alternate_Callout_Parameter : IGlassBase 
	{
								/// <summary>
					/// The Background Color field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 91dd4ef4-1f40-49d3-b61a-8fc457b4df35</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Alternate_Callout_ParameterConstants.Background_ColorFieldName)]
					Guid Background_Color  {get; set;}
			
								/// <summary>
					/// The Hide Background on Mobile field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: e9bc0ea3-9cb9-48fb-b05d-be7a5cbb4ea7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Alternate_Callout_ParameterConstants.Hide_Background_On_MobileFieldName)]
					bool Hide_Background_On_Mobile  {get; set;}
			
								/// <summary>
					/// The Image Align field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: dc9ea9da-f73c-49db-a40b-7ee9a2567afe</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Alternate_Callout_ParameterConstants.Image_AlignFieldName)]
					Guid Image_Align  {get; set;}
			
				}


	public static partial class I_Alternate_Callout_ParameterConstants{

			public const string TemplateIdString = "0876cc35-a32e-4baa-88d6-644ed9eebfd4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_alternate callout parameter";

					
			public static readonly ID Background_ColorFieldId = new ID("91dd4ef4-1f40-49d3-b61a-8fc457b4df35");
			public const string Background_ColorFieldName = "Background Color";
			
					
			public static readonly ID Hide_Background_On_MobileFieldId = new ID("e9bc0ea3-9cb9-48fb-b05d-be7a5cbb4ea7");
			public const string Hide_Background_On_MobileFieldName = "Hide Background on Mobile";
			
					
			public static readonly ID Image_AlignFieldId = new ID("dc9ea9da-f73c-49db-a40b-7ee9a2567afe");
			public const string Image_AlignFieldName = "Image Align";
			
			
	}
}
namespace CodeTest.Feature.GenericCallout.Models.GlassModels
{


	/// <summary>
	/// I_AlignImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Alternate Callout/_alignImage</para>	
	/// <para>ID: 199d737d-7f8f-4289-aea6-a936ed32b572</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_AlignImageConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_AlignImage : IGlassBase 
	{
								/// <summary>
					/// The Align Type field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 0940e3f7-e825-439b-99ba-a41ed4cb9798</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_AlignImageConstants.Align_TypeFieldName)]
					string Align_Type  {get; set;}
			
				}


	public static partial class I_AlignImageConstants{

			public const string TemplateIdString = "199d737d-7f8f-4289-aea6-a936ed32b572";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_alignImage";

					
			public static readonly ID Align_TypeFieldId = new ID("0940e3f7-e825-439b-99ba-a41ed4cb9798");
			public const string Align_TypeFieldName = "Align Type";
			
			
	}
}
namespace CodeTest.Feature.GenericCallout.Models.GlassModels
{


	/// <summary>
	/// I_Alternate_Callout Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Alternate Callout/_alternate callout</para>	
	/// <para>ID: 20cfb66c-faaf-4959-bd52-469664fd7439</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Alternate_CalloutConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Alternate_Callout : IGlassBase 
	{
				
								/// <summary>
					/// The Content field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 54b7b642-b4d1-42bc-8c41-84befb88e805</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Alternate_CalloutConstants.ContentFieldName)]
					string Content  {get; set;}
			
								/// <summary>
					
								/// <summary>
					/// The Secondary Content field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 2a1587fb-96bc-46d0-a0b8-1f0f820397e0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Alternate_CalloutConstants.Secondary_ContentFieldName)]
					string Secondary_Content  {get; set;}
			
				}


	public static partial class I_Alternate_CalloutConstants{

			public const string TemplateIdString = "20cfb66c-faaf-4959-bd52-469664fd7439";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_alternate callout";

					
			public static readonly ID Background_ImageFieldId = new ID("036e2e36-d0c1-4aba-8c81-7227d1dcfed7");
			public const string Background_ImageFieldName = "Background Image";
			
					
			public static readonly ID ContentFieldId = new ID("54b7b642-b4d1-42bc-8c41-84befb88e805");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID Mobile_Background_ImageFieldId = new ID("70bacb9d-9701-47c0-bcbb-5eccfe8a1c0f");
			public const string Mobile_Background_ImageFieldName = "Mobile Background Image";
			
					
			public static readonly ID Secondary_ContentFieldId = new ID("2a1587fb-96bc-46d0-a0b8-1f0f820397e0");
			public const string Secondary_ContentFieldName = "Secondary Content";
			
			
	}
}
namespace CodeTest.Feature.GenericCallout.Models.GlassModels
{


	/// <summary>
	/// I_BgColor Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Alternate Callout/_bgColor</para>	
	/// <para>ID: 3c203a8f-cfc9-4465-8546-b1fc61c20b0e</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_BgColorConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_BgColor : IGlassBase 
	{
								/// <summary>
					/// The Color field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e8ff2698-e2df-4c6a-bebe-a5c30e2b2062</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_BgColorConstants.ColorFieldName)]
					string Color  {get; set;}
			
				}


	public static partial class I_BgColorConstants{

			public const string TemplateIdString = "3c203a8f-cfc9-4465-8546-b1fc61c20b0e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_bgColor";

					
			public static readonly ID ColorFieldId = new ID("e8ff2698-e2df-4c6a-bebe-a5c30e2b2062");
			public const string ColorFieldName = "Color";
			
			
	}
}
namespace CodeTest.Feature.GenericCallout.Models.GlassModels
{


	/// <summary>
	/// I_Alternate_Callout_Parameter_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Alternate Callout/_alternate callout parameter folder</para>	
	/// <para>ID: b03c7452-8d19-441e-89ea-de187d9d56f5</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Alternate_Callout_Parameter_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Alternate_Callout_Parameter_Folder : IGlassBase 
	{
				}


	public static partial class I_Alternate_Callout_Parameter_FolderConstants{

			public const string TemplateIdString = "b03c7452-8d19-441e-89ea-de187d9d56f5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_alternate callout parameter folder";

			
	}
}
