





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using CodeTest.Foundation.ORM.Models;




namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// ISitemap_Search_Engine Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Foundation/Sitemap XML/Sitemap Search Engine</para>	
	/// <para>ID: 122ff533-9564-4ada-a1c8-e7b1385b89de</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISitemap_Search_EngineConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISitemap_Search_Engine : IGlassBase 
	{
								/// <summary>
					/// The Sitemap Submission Uri field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8d87e400-2450-4cde-91b7-ed2f8183f909</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISitemap_Search_EngineConstants.Sitemap_Submission_UriFieldName)]
					string Sitemap_Submission_Uri  {get; set;}
			
				}


	public static partial class ISitemap_Search_EngineConstants{

			public const string TemplateIdString = "122ff533-9564-4ada-a1c8-e7b1385b89de";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Sitemap Search Engine";

					
			public static readonly ID Sitemap_Submission_UriFieldId = new ID("8d87e400-2450-4cde-91b7-ed2f8183f909");
			public const string Sitemap_Submission_UriFieldName = "Sitemap Submission Uri";
			
			
	}
}
namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// ISettings Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Foundation/Multisite/Settings</para>	
	/// <para>ID: 33927a43-078a-4a2b-9d00-01f97e5d3b0b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISettingsConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISettings : IGlassBase 
	{
								/// <summary>
					/// The Body Code field.
					/// <para>Add JavaScript code to the body of the HTML</para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: eb732efb-f3ec-4b0b-b3c9-e588b7de2d0c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Body_CodeFieldName)]
					string Body_Code  {get; set;}
			
								/// <summary>
					/// The Footer Code field.
					/// <para>Add JavaScript code to the bottom of the HTML</para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: e2678e5f-8308-495b-9bd8-a9bb2446ae70</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Footer_CodeFieldName)]
					string Footer_Code  {get; set;}
			
								/// <summary>
					/// The Head Code field.
					/// <para>Add JavaScript code to the top of the HTML (use sparingly):</para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 99b98233-3d9d-44ed-a790-0aaf20cab328</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Head_CodeFieldName)]
					string Head_Code  {get; set;}
			
								/// <summary>
					/// The Fav Icon field.
					/// <para></para>
					/// <para>Field Type: File</para>		
					/// <para>Field ID: c1ff5937-6afa-4faf-9bca-5252ee0f94ba</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Fav_IconFieldName)]
					File Fav_Icon  {get; set;}
			
								/// <summary>
					/// The SupportedLanguages field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: ecbe5535-7811-4eaa-b7d0-07ca4973586d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.SupportedLanguagesFieldName)]
					IEnumerable<Guid> SupportedLanguages  {get; set;}
			
								/// <summary>
					/// The CheckStockLocation field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 44f34fe4-16f2-4aac-938b-cdb05298606c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.CheckStockLocationFieldName)]
					Guid CheckStockLocation  {get; set;}
			
								/// <summary>
					/// The Location Map field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 5a45f527-a5bf-4c62-9556-d3e441b86109</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Location_MapFieldName)]
					Guid Location_Map  {get; set;}
			
								/// <summary>
					/// The Product Composition field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: f3b93cc3-57d4-4209-a633-0adf214c3a6b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Product_CompositionFieldName)]
					Guid Product_Composition  {get; set;}
			
								/// <summary>
					/// The Article Topics field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 850a782a-e186-4191-9d9e-c31cddf39d46</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Article_TopicsFieldName)]
					Guid Article_Topics  {get; set;}
			
								/// <summary>
					/// The Article Types field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: fe5e6d34-ba49-409a-b1c3-7c319e31138a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Article_TypesFieldName)]
					Guid Article_Types  {get; set;}
			
								/// <summary>
					/// The Global Search Page field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 1c89f895-7168-4adf-af53-437dd29c70de</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Global_Search_PageFieldName)]
					Guid Global_Search_Page  {get; set;}
			
								/// <summary>
					/// The Sales Contacts field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 17939e2a-918e-4b45-9098-c50eecd31cc2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISettingsConstants.Sales_ContactsFieldName)]
					Guid Sales_Contacts  {get; set;}
			
				}


	public static partial class ISettingsConstants{

			public const string TemplateIdString = "33927a43-078a-4a2b-9d00-01f97e5d3b0b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Settings";

					
			public static readonly ID Body_CodeFieldId = new ID("eb732efb-f3ec-4b0b-b3c9-e588b7de2d0c");
			public const string Body_CodeFieldName = "Body Code";
			
					
			public static readonly ID Footer_CodeFieldId = new ID("e2678e5f-8308-495b-9bd8-a9bb2446ae70");
			public const string Footer_CodeFieldName = "Footer Code";
			
					
			public static readonly ID Head_CodeFieldId = new ID("99b98233-3d9d-44ed-a790-0aaf20cab328");
			public const string Head_CodeFieldName = "Head Code";
			
					
			public static readonly ID Fav_IconFieldId = new ID("c1ff5937-6afa-4faf-9bca-5252ee0f94ba");
			public const string Fav_IconFieldName = "Fav Icon";
			
					
			public static readonly ID SupportedLanguagesFieldId = new ID("ecbe5535-7811-4eaa-b7d0-07ca4973586d");
			public const string SupportedLanguagesFieldName = "SupportedLanguages";
			
					
			public static readonly ID CheckStockLocationFieldId = new ID("44f34fe4-16f2-4aac-938b-cdb05298606c");
			public const string CheckStockLocationFieldName = "CheckStockLocation";
			
					
			public static readonly ID Location_MapFieldId = new ID("5a45f527-a5bf-4c62-9556-d3e441b86109");
			public const string Location_MapFieldName = "Location Map";
			
					
			public static readonly ID Product_CompositionFieldId = new ID("f3b93cc3-57d4-4209-a633-0adf214c3a6b");
			public const string Product_CompositionFieldName = "Product Composition";
			
					
			public static readonly ID Article_TopicsFieldId = new ID("850a782a-e186-4191-9d9e-c31cddf39d46");
			public const string Article_TopicsFieldName = "Article Topics";
			
					
			public static readonly ID Article_TypesFieldId = new ID("fe5e6d34-ba49-409a-b1c3-7c319e31138a");
			public const string Article_TypesFieldName = "Article Types";
			
					
			public static readonly ID Global_Search_PageFieldId = new ID("1c89f895-7168-4adf-af53-437dd29c70de");
			public const string Global_Search_PageFieldName = "Global Search Page";
			
					
			public static readonly ID Sales_ContactsFieldId = new ID("17939e2a-918e-4b45-9098-c50eecd31cc2");
			public const string Sales_ContactsFieldName = "Sales Contacts";
			
			
	}
}
namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// ITenant Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Foundation/Multisite/Tenant</para>	
	/// <para>ID: 63531d06-bb99-4ee0-84c3-affda38d47ae</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITenantConstants.TemplateIdString )] //, Cachable = true
	public partial interface ITenant : IGlassBase 
	{
				}


	public static partial class ITenantConstants{

			public const string TemplateIdString = "63531d06-bb99-4ee0-84c3-affda38d47ae";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Tenant";

			
	}
}
namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// IData_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Foundation/Multisite/Data Folder</para>	
	/// <para>ID: 66d53ba9-927a-47d9-86ca-fa9f47e14be0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IData_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IData_Folder : IGlassBase 
	{
				}


	public static partial class IData_FolderConstants{

			public const string TemplateIdString = "66d53ba9-927a-47d9-86ca-fa9f47e14be0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Data Folder";

			
	}
}
namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// ISiteRootItem Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Foundation/Multisite/SiteRootItem</para>	
	/// <para>ID: 6f1d43d4-aa76-4d25-a454-7cee9179a087</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteRootItemConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISiteRootItem : IGlassBase 
	{
								/// <summary>
					/// The Setting field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 0b2e4528-2606-4f07-b31d-c89f4629b228</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteRootItemConstants.SettingFieldName)]
					Guid Setting  {get; set;}
			
				}


	public static partial class ISiteRootItemConstants{

			public const string TemplateIdString = "6f1d43d4-aa76-4d25-a454-7cee9179a087";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteRootItem";

					
			public static readonly ID SettingFieldId = new ID("0b2e4528-2606-4f07-b31d-c89f4629b228");
			public const string SettingFieldName = "Setting";
			
			
	}
}
namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Foundation/Multisite/Home</para>	
	/// <para>ID: 82ec448d-2dca-4254-a860-24d970e30e29</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome : IGlassBase 
	{
				}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "82ec448d-2dca-4254-a860-24d970e30e29";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

			
	}
}
namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// ISitemap_Configuration Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Foundation/Sitemap XML/Sitemap Configuration</para>	
	/// <para>ID: b1d42aac-82ef-43ef-9eea-784f655b8f04</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISitemap_ConfigurationConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISitemap_Configuration : IGlassBase 
	{
								/// <summary>
					/// The Enabled Templates field.
					/// <para></para>
					/// <para>Field Type: TreelistEx</para>		
					/// <para>Field ID: 1452d535-ba8b-4a66-9a87-67d05a6e2058</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISitemap_ConfigurationConstants.Enabled_TemplatesFieldName)]
					IEnumerable<Guid> Enabled_Templates  {get; set;}
			
								/// <summary>
					/// The Excluded Items field.
					/// <para></para>
					/// <para>Field Type: TreelistEx</para>		
					/// <para>Field ID: 76002e61-2397-4b4d-84b2-98c2a8468d5a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISitemap_ConfigurationConstants.Excluded_ItemsFieldName)]
					IEnumerable<Guid> Excluded_Items  {get; set;}
			
								/// <summary>
					/// The File Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e461eaab-12a1-4f94-bfaf-0f1f88d0715d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISitemap_ConfigurationConstants.File_NameFieldName)]
					string File_Name  {get; set;}
			
								/// <summary>
					/// The Server Url field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 5043c9c2-a6ac-492c-8c1a-f7afecf77d46</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISitemap_ConfigurationConstants.Server_UrlFieldName)]
					string Server_Url  {get; set;}
			
								/// <summary>
					/// The Search Engines field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: 6bf47032-530c-4df3-9b29-0849e0990319</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISitemap_ConfigurationConstants.Search_EnginesFieldName)]
					IEnumerable<Guid> Search_Engines  {get; set;}
			
				}


	public static partial class ISitemap_ConfigurationConstants{

			public const string TemplateIdString = "b1d42aac-82ef-43ef-9eea-784f655b8f04";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Sitemap Configuration";

					
			public static readonly ID Enabled_TemplatesFieldId = new ID("1452d535-ba8b-4a66-9a87-67d05a6e2058");
			public const string Enabled_TemplatesFieldName = "Enabled Templates";
			
					
			public static readonly ID Excluded_ItemsFieldId = new ID("76002e61-2397-4b4d-84b2-98c2a8468d5a");
			public const string Excluded_ItemsFieldName = "Excluded Items";
			
					
			public static readonly ID File_NameFieldId = new ID("e461eaab-12a1-4f94-bfaf-0f1f88d0715d");
			public const string File_NameFieldName = "File Name";
			
					
			public static readonly ID Server_UrlFieldId = new ID("5043c9c2-a6ac-492c-8c1a-f7afecf77d46");
			public const string Server_UrlFieldName = "Server Url";
			
					
			public static readonly ID Search_EnginesFieldId = new ID("6bf47032-530c-4df3-9b29-0849e0990319");
			public const string Search_EnginesFieldName = "Search Engines";
			
			
	}
}
namespace CodeTest.Foundation.ORM.Models.GlassModels
{


	/// <summary>
	/// IShared_Content_Definition Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Foundation/Sitemap XML/Shared Content Definition</para>	
	/// <para>ID: cb547f2d-4c51-4ab3-824c-03439fb89fa6</para>	
	/// </summary>
	[SitecoreType(TemplateId=IShared_Content_DefinitionConstants.TemplateIdString )] //, Cachable = true
	public partial interface IShared_Content_Definition : IGlassBase 
	{
								/// <summary>
					/// The Content Location field.
					/// <para></para>
					/// <para>Field Type: Datasource</para>		
					/// <para>Field ID: 1ce7e08f-8e51-450f-955e-2f7c921a96c8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IShared_Content_DefinitionConstants.Content_LocationFieldName)]
					object /* UNKNOWN */ Content_Location  {get; set;}
			
								/// <summary>
					/// The Parent Item field.
					/// <para></para>
					/// <para>Field Type: Datasource</para>		
					/// <para>Field ID: aa4769b3-9f9f-4628-b3cd-2536b25920ca</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IShared_Content_DefinitionConstants.Parent_ItemFieldName)]
					object /* UNKNOWN */ Parent_Item  {get; set;}
			
				}


	public static partial class IShared_Content_DefinitionConstants{

			public const string TemplateIdString = "cb547f2d-4c51-4ab3-824c-03439fb89fa6";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Shared Content Definition";

					
			public static readonly ID Content_LocationFieldId = new ID("1ce7e08f-8e51-450f-955e-2f7c921a96c8");
			public const string Content_LocationFieldName = "Content Location";
			
					
			public static readonly ID Parent_ItemFieldId = new ID("aa4769b3-9f9f-4628-b3cd-2536b25920ca");
			public const string Parent_ItemFieldName = "Parent Item";
			
			
	}
}
