





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using CodeTest.Foundation.ORM.Models;




namespace CodeTest.Feature.HeroSlider.Models.GlassModels
{


	/// <summary>
	/// I_ContentPosition Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Hero Slider/_contentPosition</para>	
	/// <para>ID: 11e2bd13-a1f3-4602-a0de-1b9fa98ff745</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_ContentPositionConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_ContentPosition : IGlassBase 
	{
								/// <summary>
					/// The Alignment field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 5e5ec7c5-3227-408d-a127-6522dc276c74</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_ContentPositionConstants.AlignmentFieldName)]
					string Alignment  {get; set;}
			
				}


	public static partial class I_ContentPositionConstants{

			public const string TemplateIdString = "11e2bd13-a1f3-4602-a0de-1b9fa98ff745";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_contentPosition";

					
			public static readonly ID AlignmentFieldId = new ID("5e5ec7c5-3227-408d-a127-6522dc276c74");
			public const string AlignmentFieldName = "Alignment";
			
			
	}
}
namespace CodeTest.Feature.HeroSlider.Models.GlassModels
{


	/// <summary>
	/// I_HeroContent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Hero Slider/Rendering parameters/_heroContent</para>	
	/// <para>ID: 6cee8e14-ebef-41a2-bd21-f5a1ca216d0c</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HeroContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HeroContent : IGlassBase 
	{
								/// <summary>
					/// The Color Theme field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 45dcde07-e807-4809-8472-2813329b9095</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HeroContentConstants.Color_ThemeFieldName)]
					Guid Color_Theme  {get; set;}
			
								/// <summary>
					/// The Text Alignment field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: f6e55be5-569f-46ec-8c9b-cf10a708887a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HeroContentConstants.Text_AlignmentFieldName)]
					Guid Text_Alignment  {get; set;}
			
				}


	public static partial class I_HeroContentConstants{

			public const string TemplateIdString = "6cee8e14-ebef-41a2-bd21-f5a1ca216d0c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_heroContent";

					
			public static readonly ID Color_ThemeFieldId = new ID("45dcde07-e807-4809-8472-2813329b9095");
			public const string Color_ThemeFieldName = "Color Theme";
			
					
			public static readonly ID Text_AlignmentFieldId = new ID("f6e55be5-569f-46ec-8c9b-cf10a708887a");
			public const string Text_AlignmentFieldName = "Text Alignment";
			
			
	}
}
namespace CodeTest.Feature.HeroSlider.Models.GlassModels
{


	/// <summary>
	/// I_Herosliderfolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Feature/Hero Slider/_herosliderfolder</para>	
	/// <para>ID: 70b37e73-a6c2-46db-9c13-f01bec12cce5</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HerosliderfolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Herosliderfolder : IGlassBase 
	{
				}


	public static partial class I_HerosliderfolderConstants{

			public const string TemplateIdString = "70b37e73-a6c2-46db-9c13-f01bec12cce5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_herosliderfolder";

			
	}
}
namespace CodeTest.Feature.HeroSlider.Models.GlassModels
{


	/// <summary>
	/// I_Theme Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Hero Slider/_theme</para>	
	/// <para>ID: ed9c28e6-50da-4846-af48-26da5c2376ec</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_ThemeConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Theme : IGlassBase 
	{
								/// <summary>
					/// The Theme field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 0a085eec-22e3-4c20-902f-8fa8794f6d43</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_ThemeConstants.ThemeFieldName)]
					string Theme  {get; set;}
			
				}


	public static partial class I_ThemeConstants{

			public const string TemplateIdString = "ed9c28e6-50da-4846-af48-26da5c2376ec";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_theme";

					
			public static readonly ID ThemeFieldId = new ID("0a085eec-22e3-4c20-902f-8fa8794f6d43");
			public const string ThemeFieldName = "Theme";
			
			
	}
}
namespace CodeTest.Feature.HeroSlider.Models.GlassModels
{


	/// <summary>
	/// I_HeroSlider Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Hero Slider/_heroSlider</para>	
	/// <para>ID: fb87d895-3a00-42fe-90e6-ae6c4c290def</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_HeroSliderConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_HeroSlider : IGlassBase 
	{
								/// <summary>
					/// The Content field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 2719dc61-60a0-41fb-8c80-8e117620ed3a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HeroSliderConstants.ContentFieldName)]
					string Content  {get; set;}
			
								/// <summary>
					/// The CTA field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 622929d4-1c87-4bb7-b3ff-d5ac1b3c04f4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HeroSliderConstants.CTAFieldName)]
					Link CTA  {get; set;}
			
								/// <summary>
					/// The Heading field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: c5adaf08-336e-47c2-9558-fe75c4666974</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HeroSliderConstants.HeadingFieldName)]
					string Heading  {get; set;}
			
								/// <summary>
					/// The Hero Image field.
					/// <para>Recommended image size 1658 x 581 pixels</para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: ca76abd6-b724-44aa-8852-0146ce69ead4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HeroSliderConstants.Hero_ImageFieldName)]
					Image Hero_Image  {get; set;}
			
								/// <summary>
					/// The Mobile Hero Image field.
					/// <para>Recommended image size 339 x 329 pixels</para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: ece44228-1361-41ee-9124-3cf3b587ae2a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_HeroSliderConstants.Mobile_Hero_ImageFieldName)]
					Image Mobile_Hero_Image  {get; set;}
			
				}


	public static partial class I_HeroSliderConstants{

			public const string TemplateIdString = "fb87d895-3a00-42fe-90e6-ae6c4c290def";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_heroSlider";

					
			public static readonly ID ContentFieldId = new ID("2719dc61-60a0-41fb-8c80-8e117620ed3a");
			public const string ContentFieldName = "Content";
			
					
			public static readonly ID CTAFieldId = new ID("622929d4-1c87-4bb7-b3ff-d5ac1b3c04f4");
			public const string CTAFieldName = "CTA";
			
					
			public static readonly ID HeadingFieldId = new ID("c5adaf08-336e-47c2-9558-fe75c4666974");
			public const string HeadingFieldName = "Heading";
			
					
			public static readonly ID Hero_ImageFieldId = new ID("ca76abd6-b724-44aa-8852-0146ce69ead4");
			public const string Hero_ImageFieldName = "Hero Image";
			
					
			public static readonly ID Mobile_Hero_ImageFieldId = new ID("ece44228-1361-41ee-9124-3cf3b587ae2a");
			public const string Mobile_Hero_ImageFieldName = "Mobile Hero Image";
			
			
	}
}
