





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using CodeTest.Foundation.ORM.Models;




namespace CodeTest.Feature.Container.Models.GlassModels
{


	/// <summary>
	/// I_BackgroundOrientation Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Feature/Containers/Rendering parameters/_backgroundOrientation</para>	
	/// <para>ID: 1bb521c5-69c0-4154-bc02-f581c9a3fb68</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_BackgroundOrientationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_BackgroundOrientation : IGlassBase 
	{
								/// <summary>
					/// The Position field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: ba8fb906-5be5-4c80-b161-b1fb21ff3c50</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_BackgroundOrientationConstants.PositionFieldName)]
					Guid Position  {get; set;}
			
				}


	public static partial class I_BackgroundOrientationConstants{

			public const string TemplateIdString = "1bb521c5-69c0-4154-bc02-f581c9a3fb68";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_backgroundOrientation";

					
			public static readonly ID PositionFieldId = new ID("ba8fb906-5be5-4c80-b161-b1fb21ff3c50");
			public const string PositionFieldName = "Position";
			
			
	}
}
namespace CodeTest.Feature.Container.Models.GlassModels
{


	/// <summary>
	/// I_BackgroundImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Allegro/AllegroMicro/Feature/Containers/_backgroundImage</para>	
	/// <para>ID: 1deda109-36a4-4038-9c2d-9835ca37726f</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_BackgroundImageConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_BackgroundImage : IGlassBase 
	{
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 4c011701-ec05-4a48-9561-4abf75beaeb8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_BackgroundImageConstants.ImageFieldName)]
					Image Image  {get; set;}
			
				}


	public static partial class I_BackgroundImageConstants{

			public const string TemplateIdString = "1deda109-36a4-4038-9c2d-9835ca37726f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_backgroundImage";

					
			public static readonly ID ImageFieldId = new ID("4c011701-ec05-4a48-9561-4abf75beaeb8");
			public const string ImageFieldName = "Image";
			
			
	}
}
namespace CodeTest.Feature.Container.Models.GlassModels
{


	/// <summary>
	/// I_BackgroundPosition Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Allegro/AllegroMicro/Feature/Containers/_backgroundPosition</para>	
	/// <para>ID: 5e131411-93d5-40a7-b49d-c1f157fad8d0</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_BackgroundPositionConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_BackgroundPosition : IGlassBase 
	{
								/// <summary>
					/// The Position Style field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 797ba12a-3774-47e4-8058-474b5e5abe3f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_BackgroundPositionConstants.Position_StyleFieldName)]
					string Position_Style  {get; set;}
			
				}


	public static partial class I_BackgroundPositionConstants{

			public const string TemplateIdString = "5e131411-93d5-40a7-b49d-c1f157fad8d0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_backgroundPosition";

					
			public static readonly ID Position_StyleFieldId = new ID("797ba12a-3774-47e4-8058-474b5e5abe3f");
			public const string Position_StyleFieldName = "Position Style";
			
			
	}
}
